import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, FileText, Radar, Sparkles, Target, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

const activityLabels = { analyst: "Analista", recruiter: "Recrutador", career_editor: "Editor de currículo", integration_guard: "Guardião de integrações" };

export default function DashboardPage() {
  const [, setLocation] = useLocation();
  const { data, isLoading } = trpc.career.dashboard.useQuery();
  if (isLoading) return <div className="space-y-6"><Skeleton className="h-48 w-full rounded-[2rem]" /><div className="grid gap-4 md:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-28 rounded-2xl" />)}</div></div>;
  const profiles = data?.profiles ?? [];
  const metrics = data?.metrics ?? { jobs: 0, recommended: 0, approved: 0, submitted: 0, averageScore: 0 };
  return <div className="mx-auto max-w-7xl space-y-7"><section className="relative overflow-hidden rounded-[2rem] bg-[#123c32] px-6 py-8 text-white shadow-[0_24px_70px_rgba(20,58,47,0.18)] sm:px-9"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full border border-white/10" /><div className="absolute right-16 top-12 h-20 w-20 rounded-full bg-[#e8b96d]/15 blur-2xl" /><div className="relative max-w-2xl"><Badge className="border-0 bg-[#e7b367] text-[#17342b] hover:bg-[#e7b367]">Espaço privado</Badge><p className="mt-5 text-xs font-bold uppercase tracking-[0.2em] text-[#aec4b8]">Direção de carreira, sem ruído</p><h1 className="mt-2 font-[var(--font-display)] text-4xl leading-[1.04] tracking-tight sm:text-5xl">Decisões melhores para cada candidatura.</h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#d7e6de]">Organize perfis independentes, centralize oportunidades e mantenha a decisão final de candidatura sempre sob seu controle.</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => setLocation("/perfis")} className="bg-[#e8b96d] text-[#18372e] hover:bg-[#f0c985]">Gerenciar perfis <ArrowRight className="ml-2 h-4 w-4" /></Button><Button onClick={() => setLocation("/oportunidades")} variant="outline" className="border-white/25 bg-transparent text-white hover:bg-white/10 hover:text-white">Explorar oportunidades</Button></div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BriefcaseBusiness} label="Vagas consolidadas" value={metrics.jobs} note="Base privada" /><Metric icon={Target} label="Recomendadas" value={metrics.recommended} note="Após análise" /><Metric icon={CheckCircle2} label="Aprovadas" value={metrics.approved} note="Aguardam envio" /><Metric icon={Sparkles} label="Aderência média" value={`${metrics.averageScore}%`} note="Perfis analisados" /></section>
    {profiles.length === 0 ? <section className="rounded-[1.75rem] border border-dashed border-[#c8d6cc] bg-[#fbfaf7] p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="mb-3 grid h-11 w-11 place-items-center rounded-2xl bg-[#eaf1ec] text-[#1f604d]"><UsersRound className="h-5 w-5" /></div><h2 className="font-[var(--font-display)] text-2xl text-[#18362d]">Comece pelo primeiro perfil.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#62746a]">Crie um perfil para cada trajetória profissional. Os dados, currículos, análises e candidaturas ficam isolados no seu espaço.</p></div><Button onClick={() => setLocation("/perfis")} className="bg-[#163f35] hover:bg-[#0c2e26]">Criar perfil</Button></div></section> : <section className="grid gap-5 lg:grid-cols-[1.4fr_0.9fr]"><Card className="border-0 bg-white shadow-[0_12px_35px_rgba(21,54,43,0.06)]"><CardContent className="p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#b5782d]">Perfis ativos</p><h2 className="mt-1 font-[var(--font-display)] text-2xl text-[#18362d]">Direções acompanhadas</h2></div><Button variant="ghost" onClick={() => setLocation("/perfis")} className="text-[#1a5948]">Ver todos <ArrowRight className="ml-1 h-4 w-4" /></Button></div><div className="mt-5 grid gap-3">{profiles.slice(0, 3).map(profile => <div key={profile.id} className="flex items-center justify-between rounded-2xl bg-[#f6f7f3] p-4"><div><p className="font-semibold text-[#203d34]">{profile.label}</p><p className="mt-1 text-xs text-[#718178]">{profile.targetRole} · {profile.seniority}</p></div><Badge variant="outline" className="border-[#cfe0d4] bg-white text-[#37705c]">{profile.professionalArea}</Badge></div>)}</div></CardContent></Card><AgentPanel /></section>}
    <section className="grid gap-5 lg:grid-cols-[1.4fr_0.9fr]"><Card className="border-0 bg-white shadow-[0_12px_35px_rgba(21,54,43,0.06)]"><CardContent className="p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#b5782d]">Atividade dos agentes</p><h2 className="mt-1 font-[var(--font-display)] text-2xl text-[#18362d]">Rastro de decisões</h2></div><Radar className="h-5 w-5 text-[#b5782d]" /></div>{data?.activities.length ? <div className="mt-5 divide-y divide-[#edf0ec]">{data.activities.map(activity => <div key={activity.id} className="py-4 first:pt-0"><div className="flex items-start justify-between gap-4"><div><p className="font-medium text-[#264238]">{activity.title}</p><p className="mt-1 text-sm leading-5 text-[#6b7c73]">{activity.detail}</p></div><Badge variant="outline" className="shrink-0 border-[#d7e1da] text-[#587066]">{activityLabels[activity.agent]}</Badge></div></div>)}</div> : <EmptyActivity />}</CardContent></Card><Card className="border-0 bg-[#edf4ef]"><CardContent className="p-6"><FileText className="h-5 w-5 text-[#27604e]" /><p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-[#5d8374]">Proteção de candidatura</p><h2 className="mt-1 font-[var(--font-display)] text-2xl leading-tight text-[#18362d]">Nenhum envio é automático.</h2><p className="mt-3 text-sm leading-6 text-[#577168]">O sistema cria rascunhos e registra a aprovação. O envio só é registrado após sua confirmação consciente na plataforma oficial.</p><Button onClick={() => setLocation("/candidaturas")} variant="outline" className="mt-6 border-[#9fc2b0] bg-white text-[#215b49] hover:bg-[#f9fcfa]">Revisar candidaturas</Button></CardContent></Card></section></div>;
}

function Metric({ icon: Icon, label, value, note }: { icon: typeof BriefcaseBusiness; label: string; value: string | number; note: string }) { return <Card className="border-0 bg-white shadow-[0_12px_35px_rgba(21,54,43,0.05)]"><CardContent className="p-5"><Icon className="h-4 w-4 text-[#bc7c2d]" /><p className="mt-4 text-2xl font-semibold tracking-tight text-[#1d392f]">{value}</p><p className="mt-1 text-sm font-medium text-[#3f574d]">{label}</p><p className="mt-1 text-xs text-[#85948c]">{note}</p></CardContent></Card>; }
function AgentPanel() { return <Card className="border-0 bg-[#f2eadc]"><CardContent className="p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#a36c29]">Três camadas de apoio</p><div className="mt-4 space-y-4"><Agent name="Analista" text="Estrutura requisitos, senioridade e modalidade." /><Agent name="Recrutador" text="Calcula aderência, lacunas e prioridade." /><Agent name="Editor ético" text="Adapta sem inventar experiências." /></div></CardContent></Card>; }
function Agent({ name, text }: { name: string; text: string }) { return <div><p className="font-semibold text-[#3d3c2e]">{name}</p><p className="mt-1 text-sm leading-5 text-[#706b57]">{text}</p></div>; }
function EmptyActivity() { return <div className="mt-5 rounded-2xl bg-[#f7f8f5] p-5 text-sm leading-6 text-[#728077]">As ações dos agentes aparecerão aqui quando você criar perfis, adicionar oportunidades ou gerar um rascunho de candidatura.</div>; }
